export const AUTO_NEXT_TRACK = "AUTO_NEXT_TRACK";
export const SWITCH_NEXT_TRACK = "SWITCH_NEXT_TRACK";
export const SWITCH_PREVIOUS_TRACK = "SWITCH_PREVIOUS_TRACK";
export const SHAKE_TRACK = "SHAKE_TRACK";