export const tracksArr = [
    {
        title: 'Run Run',
        subtitle: '(feat. AR/CO)',
        author: 'Jaded, Will Clarke, AR/CO',
        album: 'Run Run',
        time: '2:52',
        titleLink: 'http://',
        id: 1,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Eyes on Fire',
        subtitle: '(Zeds Dead Remix)',
        author: 'Blue Foundation, Zeds Dead',
        album: 'Eyes on Fire',
        time: '5:22',
        titleLink: 'http://',
        id: 2,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Mucho Bien',
        subtitle: '(Hi Prodsfile Remix)',
        author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
        album: 'Mucho Bien',
        time: '3:42',
        titleLink: 'http://',
        id: 3,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cherries',
        subtitle: 'dg',
        author: 'minthaze',
        album: 'Captivatxing',
        time: '1:42',
        titleLink: 'http://',
        id: 11,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cheies',
        subtitle: 'dxcgsb',
        author: 'minthatze',
        album: 'Captivatxcing',
        time: '1:42',
        titleLink: 'http://',
        id: 4,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cherris',
        subtitle: 'cxdsfgvb',
        author: 'minthadbze',
        album: 'Captzxivating',
        time: '1:42',
        titleLink: 'http://',
        id: 5,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cherries',
        subtitle: 'ddsfgg',
        author: 'minthaze',
        album: 'Captivatxing',
        time: '1:42',
        titleLink: 'http://',
        id: 6,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cheies',
        subtitle: 'dxcsdgfdfvb',
        author: 'minthadbze',
        album: 'Captzxivating',
        time: '1:42',
        titleLink: 'http://',
        id: 7,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cherries',
        subtitle: 'ddgg',
        author: 'minthaze',
        album: 'Captivatxing',
        time: '1:42',
        titleLink: 'http://',
        id: 8,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cheies',
        subtitle: 'dxzgdxcb',
        author: 'minthatze',
        album: 'Captivatxcing',
        time: '1:42',
        titleLink: 'http://',
        id: 23,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cherris',
        subtitle: 'cxxzcvvb',
        author: 'minthadbze',
        album: 'Captzxivating',
        time: '1:42',
        titleLink: 'http://',
        id: 234,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cheies',
        subtitle: 'dxcsdgfdfvb',
        author: 'minthadbze',
        album: 'Captzxivating',
        time: '1:42',
        titleLink: 'http://',
        id: 12,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cherries',
        subtitle: 'ddgg',
        author: 'minthaze',
        album: 'Captivatxing',
        time: '1:42',
        titleLink: 'http://',
        id: 13,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cheies',
        subtitle: 'dxzgdxcb',
        author: 'minthatze',
        album: 'Captivatxcing',
        time: '1:42',
        titleLink: 'http://',
        id: 24,
        authorLink: 'http://',
        albumLink: 'http://',
    },
    {
        title: 'Knives n Cherris',
        subtitle: 'cxxzcvvb',
        author: 'minthadbze',
        album: 'Captzxivating',
        time: '1:42',
        titleLink: 'http://',
        id: 10,
        authorLink: 'http://',
        albumLink: 'http://',
    },
]
